#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DirectFNCRM
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HisseSinyal")]
	public partial class HisseSinyalDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertT_Member(T_Member instance);
    partial void UpdateT_Member(T_Member instance);
    partial void DeleteT_Member(T_Member instance);
    #endregion
		
		public HisseSinyalDataContext() : 
				base(global::DirectFNCRM.Properties.Settings.Default.HisseSinyalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HisseSinyalDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HisseSinyalDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HisseSinyalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HisseSinyalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<T_Member> T_Members
		{
			get
			{
				return this.GetTable<T_Member>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Member")]
	public partial class T_Member : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Member_TCKN;
		
		private string _Member_Name;
		
		private string _Member_Surname;
		
		private string _Member_Fullname;
		
		private string _Member_Phone;
		
		private string _Member_Email;
		
		private string _Member_Password;
		
		private string _Member_GUID;
		
		private string _Member_SessionID;
		
		private System.Nullable<System.DateTime> _Member_Birthday;
		
		private string _Member_City;
		
		private string _Member_Country;
		
		private string _Member_Address;
		
		private string _Member_PostalCode;
		
		private string _Member_Licences;
		
		private System.DateTime _Member_LicenceEndDate;
		
		private System.DateTime _Member_LastLogin;
		
		private string _Member_InvestmentType;
		
		private string _Member_Notes;
		
		private bool _kvkkAccepted;
		
		private bool _isSuspended;
		
		private bool _isActive;
		
		private bool _isDeleted;
		
		private System.DateTime _createdOn;
		
		private System.Nullable<bool> _isAdmin;
		
		private System.Nullable<bool> _electronicAccepted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMember_TCKNChanging(string value);
    partial void OnMember_TCKNChanged();
    partial void OnMember_NameChanging(string value);
    partial void OnMember_NameChanged();
    partial void OnMember_SurnameChanging(string value);
    partial void OnMember_SurnameChanged();
    partial void OnMember_FullnameChanging(string value);
    partial void OnMember_FullnameChanged();
    partial void OnMember_PhoneChanging(string value);
    partial void OnMember_PhoneChanged();
    partial void OnMember_EmailChanging(string value);
    partial void OnMember_EmailChanged();
    partial void OnMember_PasswordChanging(string value);
    partial void OnMember_PasswordChanged();
    partial void OnMember_GUIDChanging(string value);
    partial void OnMember_GUIDChanged();
    partial void OnMember_SessionIDChanging(string value);
    partial void OnMember_SessionIDChanged();
    partial void OnMember_BirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnMember_BirthdayChanged();
    partial void OnMember_CityChanging(string value);
    partial void OnMember_CityChanged();
    partial void OnMember_CountryChanging(string value);
    partial void OnMember_CountryChanged();
    partial void OnMember_AddressChanging(string value);
    partial void OnMember_AddressChanged();
    partial void OnMember_PostalCodeChanging(string value);
    partial void OnMember_PostalCodeChanged();
    partial void OnMember_LicencesChanging(string value);
    partial void OnMember_LicencesChanged();
    partial void OnMember_LicenceEndDateChanging(System.DateTime value);
    partial void OnMember_LicenceEndDateChanged();
    partial void OnMember_LastLoginChanging(System.DateTime value);
    partial void OnMember_LastLoginChanged();
    partial void OnMember_InvestmentTypeChanging(string value);
    partial void OnMember_InvestmentTypeChanged();
    partial void OnMember_NotesChanging(string value);
    partial void OnMember_NotesChanged();
    partial void OnkvkkAcceptedChanging(bool value);
    partial void OnkvkkAcceptedChanged();
    partial void OnisSuspendedChanging(bool value);
    partial void OnisSuspendedChanged();
    partial void OnisActiveChanging(bool value);
    partial void OnisActiveChanged();
    partial void OnisDeletedChanging(bool value);
    partial void OnisDeletedChanged();
    partial void OncreatedOnChanging(System.DateTime value);
    partial void OncreatedOnChanged();
    partial void OnisAdminChanging(System.Nullable<bool> value);
    partial void OnisAdminChanged();
    partial void OnelectronicAcceptedChanging(System.Nullable<bool> value);
    partial void OnelectronicAcceptedChanged();
    #endregion
		
		public T_Member()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_TCKN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_TCKN
		{
			get
			{
				return this._Member_TCKN;
			}
			set
			{
				if ((this._Member_TCKN != value))
				{
					this.OnMember_TCKNChanging(value);
					this.SendPropertyChanging();
					this._Member_TCKN = value;
					this.SendPropertyChanged("Member_TCKN");
					this.OnMember_TCKNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Name
		{
			get
			{
				return this._Member_Name;
			}
			set
			{
				if ((this._Member_Name != value))
				{
					this.OnMember_NameChanging(value);
					this.SendPropertyChanging();
					this._Member_Name = value;
					this.SendPropertyChanged("Member_Name");
					this.OnMember_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Surname
		{
			get
			{
				return this._Member_Surname;
			}
			set
			{
				if ((this._Member_Surname != value))
				{
					this.OnMember_SurnameChanging(value);
					this.SendPropertyChanging();
					this._Member_Surname = value;
					this.SendPropertyChanged("Member_Surname");
					this.OnMember_SurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Fullname", AutoSync=AutoSync.Always, DbType="VarChar(101) NOT NULL", CanBeNull=false, IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string Member_Fullname
		{
			get
			{
				return this._Member_Fullname;
			}
			set
			{
				if ((this._Member_Fullname != value))
				{
					this.OnMember_FullnameChanging(value);
					this.SendPropertyChanging();
					this._Member_Fullname = value;
					this.SendPropertyChanged("Member_Fullname");
					this.OnMember_FullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Phone", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Phone
		{
			get
			{
				return this._Member_Phone;
			}
			set
			{
				if ((this._Member_Phone != value))
				{
					this.OnMember_PhoneChanging(value);
					this.SendPropertyChanging();
					this._Member_Phone = value;
					this.SendPropertyChanged("Member_Phone");
					this.OnMember_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Email
		{
			get
			{
				return this._Member_Email;
			}
			set
			{
				if ((this._Member_Email != value))
				{
					this.OnMember_EmailChanging(value);
					this.SendPropertyChanging();
					this._Member_Email = value;
					this.SendPropertyChanged("Member_Email");
					this.OnMember_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Password
		{
			get
			{
				return this._Member_Password;
			}
			set
			{
				if ((this._Member_Password != value))
				{
					this.OnMember_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Member_Password = value;
					this.SendPropertyChanged("Member_Password");
					this.OnMember_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_GUID", DbType="VarChar(150)")]
		public string Member_GUID
		{
			get
			{
				return this._Member_GUID;
			}
			set
			{
				if ((this._Member_GUID != value))
				{
					this.OnMember_GUIDChanging(value);
					this.SendPropertyChanging();
					this._Member_GUID = value;
					this.SendPropertyChanged("Member_GUID");
					this.OnMember_GUIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_SessionID", DbType="VarChar(150)")]
		public string Member_SessionID
		{
			get
			{
				return this._Member_SessionID;
			}
			set
			{
				if ((this._Member_SessionID != value))
				{
					this.OnMember_SessionIDChanging(value);
					this.SendPropertyChanging();
					this._Member_SessionID = value;
					this.SendPropertyChanged("Member_SessionID");
					this.OnMember_SessionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Birthday", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Member_Birthday
		{
			get
			{
				return this._Member_Birthday;
			}
			set
			{
				if ((this._Member_Birthday != value))
				{
					this.OnMember_BirthdayChanging(value);
					this.SendPropertyChanging();
					this._Member_Birthday = value;
					this.SendPropertyChanged("Member_Birthday");
					this.OnMember_BirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_City", DbType="VarChar(50)")]
		public string Member_City
		{
			get
			{
				return this._Member_City;
			}
			set
			{
				if ((this._Member_City != value))
				{
					this.OnMember_CityChanging(value);
					this.SendPropertyChanging();
					this._Member_City = value;
					this.SendPropertyChanged("Member_City");
					this.OnMember_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Country", DbType="VarChar(50)")]
		public string Member_Country
		{
			get
			{
				return this._Member_Country;
			}
			set
			{
				if ((this._Member_Country != value))
				{
					this.OnMember_CountryChanging(value);
					this.SendPropertyChanging();
					this._Member_Country = value;
					this.SendPropertyChanged("Member_Country");
					this.OnMember_CountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Address", DbType="VarChar(100)")]
		public string Member_Address
		{
			get
			{
				return this._Member_Address;
			}
			set
			{
				if ((this._Member_Address != value))
				{
					this.OnMember_AddressChanging(value);
					this.SendPropertyChanging();
					this._Member_Address = value;
					this.SendPropertyChanged("Member_Address");
					this.OnMember_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_PostalCode", DbType="VarChar(50)")]
		public string Member_PostalCode
		{
			get
			{
				return this._Member_PostalCode;
			}
			set
			{
				if ((this._Member_PostalCode != value))
				{
					this.OnMember_PostalCodeChanging(value);
					this.SendPropertyChanging();
					this._Member_PostalCode = value;
					this.SendPropertyChanged("Member_PostalCode");
					this.OnMember_PostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Licences", DbType="VarChar(50)")]
		public string Member_Licences
		{
			get
			{
				return this._Member_Licences;
			}
			set
			{
				if ((this._Member_Licences != value))
				{
					this.OnMember_LicencesChanging(value);
					this.SendPropertyChanging();
					this._Member_Licences = value;
					this.SendPropertyChanged("Member_Licences");
					this.OnMember_LicencesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_LicenceEndDate", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Member_LicenceEndDate
		{
			get
			{
				return this._Member_LicenceEndDate;
			}
			set
			{
				if ((this._Member_LicenceEndDate != value))
				{
					this.OnMember_LicenceEndDateChanging(value);
					this.SendPropertyChanging();
					this._Member_LicenceEndDate = value;
					this.SendPropertyChanged("Member_LicenceEndDate");
					this.OnMember_LicenceEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_LastLogin", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Member_LastLogin
		{
			get
			{
				return this._Member_LastLogin;
			}
			set
			{
				if ((this._Member_LastLogin != value))
				{
					this.OnMember_LastLoginChanging(value);
					this.SendPropertyChanging();
					this._Member_LastLogin = value;
					this.SendPropertyChanged("Member_LastLogin");
					this.OnMember_LastLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_InvestmentType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_InvestmentType
		{
			get
			{
				return this._Member_InvestmentType;
			}
			set
			{
				if ((this._Member_InvestmentType != value))
				{
					this.OnMember_InvestmentTypeChanging(value);
					this.SendPropertyChanging();
					this._Member_InvestmentType = value;
					this.SendPropertyChanged("Member_InvestmentType");
					this.OnMember_InvestmentTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Member_Notes", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Member_Notes
		{
			get
			{
				return this._Member_Notes;
			}
			set
			{
				if ((this._Member_Notes != value))
				{
					this.OnMember_NotesChanging(value);
					this.SendPropertyChanging();
					this._Member_Notes = value;
					this.SendPropertyChanged("Member_Notes");
					this.OnMember_NotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kvkkAccepted", DbType="Bit NOT NULL")]
		public bool kvkkAccepted
		{
			get
			{
				return this._kvkkAccepted;
			}
			set
			{
				if ((this._kvkkAccepted != value))
				{
					this.OnkvkkAcceptedChanging(value);
					this.SendPropertyChanging();
					this._kvkkAccepted = value;
					this.SendPropertyChanged("kvkkAccepted");
					this.OnkvkkAcceptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSuspended", DbType="Bit NOT NULL")]
		public bool isSuspended
		{
			get
			{
				return this._isSuspended;
			}
			set
			{
				if ((this._isSuspended != value))
				{
					this.OnisSuspendedChanging(value);
					this.SendPropertyChanging();
					this._isSuspended = value;
					this.SendPropertyChanged("isSuspended");
					this.OnisSuspendedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit NOT NULL")]
		public bool isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isDeleted", DbType="Bit NOT NULL")]
		public bool isDeleted
		{
			get
			{
				return this._isDeleted;
			}
			set
			{
				if ((this._isDeleted != value))
				{
					this.OnisDeletedChanging(value);
					this.SendPropertyChanging();
					this._isDeleted = value;
					this.SendPropertyChanged("isDeleted");
					this.OnisDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdOn", DbType="SmallDateTime NOT NULL")]
		public System.DateTime createdOn
		{
			get
			{
				return this._createdOn;
			}
			set
			{
				if ((this._createdOn != value))
				{
					this.OncreatedOnChanging(value);
					this.SendPropertyChanging();
					this._createdOn = value;
					this.SendPropertyChanged("createdOn");
					this.OncreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isAdmin", DbType="Bit")]
		public System.Nullable<bool> isAdmin
		{
			get
			{
				return this._isAdmin;
			}
			set
			{
				if ((this._isAdmin != value))
				{
					this.OnisAdminChanging(value);
					this.SendPropertyChanging();
					this._isAdmin = value;
					this.SendPropertyChanged("isAdmin");
					this.OnisAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_electronicAccepted", DbType="Bit")]
		public System.Nullable<bool> electronicAccepted
		{
			get
			{
				return this._electronicAccepted;
			}
			set
			{
				if ((this._electronicAccepted != value))
				{
					this.OnelectronicAcceptedChanging(value);
					this.SendPropertyChanging();
					this._electronicAccepted = value;
					this.SendPropertyChanged("electronicAccepted");
					this.OnelectronicAcceptedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
